CXX = g++
CXXFLAGS = -g -o0 --std=c++11

insert_into_sorted_linked: insert_into_sorted_linked.o
	$(CXX) $(CXXFLAGS) insert_into_sorted_linked.cpp -o insert_into_sorted_linked.exe

median_sorted_linked: median_sorted_linked.o
	$(CXX) $(CXXFLAGS) median_sorted_linked.cpp -o median_sorted_linked.exe